---
title: "shapes"
output: html_document
date: '2022-05-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gplots)
```


```{r}
createNLcolumns <- function(dataframe, order){
  nList <- vector(mode="list")
  liList <- vector(mode="list")
  lList <- vector(mode="list")
  for(n in 0:order){
    for (li in 0:(n%/%2)){
	     nList <- append(nList, n)
	     liList <- append(liList, li)
	     lList <- append(lList, li*2 + as.numeric(n%%2!=0))
	  }
  }
  
  nList <- rep(nList, nrow(dataframe)/length(nList))
  liList <- rep(liList, nrow(dataframe)/length(liList))
  lList <- rep(lList, nrow(dataframe)/length(lList))
  new_cols <- data.frame("n"=unlist(nList), "li"=unlist(liList), "l"=unlist(lList))
  return(new_cols)
  
}
```


```{r}
createIndexName <- function(dataframe){
  vec <- vector(mode = "list")
  for(i in 1:nrow(dataframe)){
    vec <- append(vec, paste("z",dataframe$n[i],",",dataframe$l[i], sep=""))
  }
  return(vec)
    
}
```


```{r}
Cubes <- read.delim("cubes.txt", header = FALSE, sep = " ", dec = ".")
colnames(Cubes)<- c("Side", "Index", "Descriptor")
new_col <-createNLcolumns(Cubes, 20)
Cubes <- cbind(Cubes, new_col)
Cubes <- cbind(Cubes, "z" = unlist(createIndexName(Cubes)))
Cubes <- subset(Cubes, Cubes$n<13)


ggplot(Cubes,aes(y=Side, x=reorder(z,Index), fill=Descriptor)) + 
  geom_raster()+
  scale_fill_viridis_c()+
  ggtitle("Descriptors for cubes")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  labs(x="Zernike descriptors (Zn,l)")

ggplot(subset(Cubes, Cubes$Side==34),aes(x=reorder(z,Index), y=Descriptor, group = 1, colour=n%%2))+
  geom_point()+
  labs(x="Zernike Descriptor (Zn,l)", y = "Descriptor value")+
  ggtitle("Descriptor for cubes (side 35)")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))




```


```{r}
Cylinders <- read.delim("cylinders.txt", header = FALSE, sep = " ", dec = ".")
Cylinders$RadiusOnHeight <- Cylinders$V1/Cylinders$V2 
colnames(Cylinders)<- c("Radius", "Height", "Index", "Descriptor", "RadiusOnEight")
new_col <-createNLcolumns(Cylinders, 20)
Cylinders <- cbind(Cylinders, new_col)
Cylinders <- cbind(Cylinders, "z" = unlist(createIndexName(Cylinders)))
Cylinders <- subset(Cylinders, Cylinders$n<13)


ggplot(Cylinders,aes(y=Radius, x=reorder(z,Index), fill=Descriptor)) + 
  geom_raster()+
  scale_fill_viridis_c()+
  ggtitle("Descriptors for cylinders") +
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  labs(x="Zernike descriptor (Zn,l)")








```
```{r}
Spheres <- read.delim("spheres.txt", header = FALSE, sep = " ", dec = ".")
colnames(Spheres)<- c("Radius", "Index", "Descriptor")
new_col <-createNLcolumns(Spheres, 20)
Spheres <- cbind(Spheres, new_col)
Spheres <- cbind(Spheres, "z" = unlist(createIndexName(Spheres)))
Spheres <- subset(Spheres, Spheres$n<13)


ggplot(Spheres,aes(y=Radius, x=reorder(z,Index), fill=Descriptor)) + 
  geom_raster()+
  scale_fill_viridis_c()+
  ggtitle("Descriptors for spheres")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  labs(x="Zernike descriptor (Zn,l)")


ggplot(subset(Spheres, Spheres$Radius==27),aes(x=reorder(z,Index), y=Descriptor,group = 1, colour=n%%2))+
  geom_point()+
  labs(x="Zernike Descriptor (Zn,l)", y = "Descriptor value")+
  ggtitle("Descriptor for sphere")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))



```


```{r}

Rotations <- read.delim("cylindersRotate.txt", header = FALSE, sep = " ", dec = ".")
colnames(Rotations)<- c("Angle", "Index", "Descriptor")
new_col <-createNLcolumns(Rotations, 20)
Rotations <- cbind(Rotations, new_col)
Rotations <- cbind(Rotations, "z" = unlist(createIndexName(Rotations)))
Rotations <-subset(Rotations, Rotations$n<13)


ggplot(Rotations,aes(y=Angle, x=reorder(z,Index), fill=Descriptor)) + 
  geom_raster()+
  scale_fill_viridis_c()+
  ggtitle("Descriptors for cylinder rotations")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  #scale_x_discrete(breaks = function(x){x[c(TRUE,FALSE,FALSE,FALSE)]})+
  labs(x="Zernike descriptor (Zn,l)", y = "Rotation angle")
  




```



```{r}
#create dataframe with error for each angle and each index
err <- 0
vec <- vector(mode="list")
for(j in unique(DataRot$Angle)){
    for(i in unique(DataRot$Index)){
      err = DataRot$Descriptor[as.numeric(DataRot$Angle==0) & as.numeric(DataRot$Index==i)]-
            DataRot$Descriptor[as.numeric(DataRot$Angle==j) & as.numeric(DataRot$Index==i)]
      vec <- append(vec, err)
    }
}

reference <- rep(DataRot$Descriptor[DataRot$Angle==0], length(unique(DataRot$Angle)))

Errors <- data.frame(DataRot$Angle, DataRot$Index, DataRot$z, unlist(vec), DataRot$Descriptor, reference) 
colnames(Errors) <- c("Angle", "Index", "z", "Error", "Descriptor", "ReferenceDescriptor")
Errors <- subset(Errors, Errors$Angle != 0)


ggplot(Errors,aes(y=Angle, x=reorder(z,Index), fill=Error)) + 
  geom_raster()+
  scale_fill_viridis_c()+
  ggtitle("Error for cylinder rotations")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))+
  labs(x="Zernike descriptor (Zn,l)")

#ggplot(DataFrameErrors,aes(y=Angle, x=reorder(z,Index), fill=(Error/((Descriptor+ReferenceDescriptor)/2)))) + 
#  geom_raster()+
#  scale_fill_viridis_c()+
#  ggtitle("Error for cylinder rotations")+
#  scale_x_discrete(breaks = function(x){x[c(TRUE,FALSE,FALSE,FALSE)]})+
#  labs(x="z")

#ggplot(DataFrameErrors,aes(y=Angle, x=reorder(z,Index), fill=(Error))) + 
#  geom_raster()+
#  scale_fill_viridis_c()+
#  ggtitle("Error for cylinder rotations")+
#  scale_x_discrete(breaks = function(x){x[c(TRUE,FALSE,FALSE,FALSE)]})+
#  labs(x="z")



#per angolo 0
ggplot(subset(DataRot, DataRot$Angle==0)[0:49,],aes(x=reorder(z,Index), y=Descriptor,group = 1, colour=n%%2))+
  geom_point()+
  labs(x="Zernike Descriptor (Zn,l)", y = "Descriptor value")+
  ggtitle("Descriptor for cylinder")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))




ggplot(DataRot,aes(x=reorder(z,Index), y=Descriptor, group = 1, colour=Angle))+
  geom_point()+
  labs(x="Zernike Descriptor (Zn,l)", y = "Descriptor value")+
  ggtitle("Descriptor for cylinder varying angle")+
  scale_x_discrete(guide=guide_axis(n.dodge=2))



```

